name: CD

on:
  workflow_call:

jobs:
  publish:
    permissions: 
      contents: read
      packages: write
    strategy:
      matrix:
        registry-url: ['https://registry.npmjs.org', 'https://npm.pkg.github.com']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: ${{ matrix.registry-url }}
      - run: npm ci
      - run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
