name: CI

on:
  push:
  pull_request:

jobs:
  Node-Transformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - uses: actions/setup-node@v3
      - run: ./node-transform.ps1 -Version "x"
        shell: pwsh
  Cleaning:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Format and Lint
        run: deno task precommit
      - run: |
          if [[ ! -z $(git status -s) ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "tpy bot"
            git commit -a -m "chore: lint & fmt"
            git push origin ${{ github.ref }}
          fi
