name: CI

on:
  push:
  pull_request:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build:verbose
      - run: cat tsc-output.cpuprofile
      - if: ${{ github.event_name }} == 'release' && ${{ github.event.action }} == 'published' && ${{ matrix.node-version }} == '18.x' && ${{ github.ref }} == 'main'
      - uses: ./.github/workflows/cd.yml
