name: CI

on:
  push:
  pull_request:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build:verbose
      - run: cat tsc-output.cpuprofile
  invoke-cd:
    needs: build
    if: ${{ github.event_name }} == 'release' && ${{ github.event.action }} == 'published' && ${{ github.ref }} == 'main'
    runs-on: ubuntu-latest
    steps:
    - run: echo "ok i pull up"
#    - uses: actions/checkout@v3
#    - uses: ./.github/workflows/cd.yml
    
