name: CI

on:
  push:
  pull_request:

permissions: write-all

jobs:
  Cleaning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Format and Lint
        run: deno task precommit
      - run: |
          if [[ ! -z $(git status -s) ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "tpy bot"
            git add .
            git commit -m "chore: deno fmt"
            git push origin ${{ github.ref }}
          fi
#       - uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}
